"""empty message

Revision ID: 4a575c7266da
Revises: 
Create Date: 2020-09-17 01:06:21.720591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a575c7266da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.Float(), nullable=False),
    sa.Column('content_density', sa.Integer(), nullable=False),
    sa.Column('content_update', sa.Integer(), nullable=False),
    sa.Column('satisfaction', sa.Integer(), nullable=False),
    sa.Column('total_rate', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('lists',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.username'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    op.create_table('ratings',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('difficulty_level', sa.Float(), nullable=False),
    sa.Column('content_density', sa.Integer(), nullable=False),
    sa.Column('content_update', sa.Integer(), nullable=False),
    sa.Column('satisfaction', sa.Integer(), nullable=False),
    sa.Column('total_rate', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.username'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    op.drop_table('lists')
    op.drop_table('users')
    op.drop_table('courses')
    # ### end Alembic commands ###
