"""empty message

Revision ID: 7c02b6b9f8e2
Revises: 
Create Date: 2020-11-01 21:51:42.864761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c02b6b9f8e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.Float(), nullable=True),
    sa.Column('content_density', sa.Integer(), nullable=True),
    sa.Column('content_update', sa.Integer(), nullable=True),
    sa.Column('satisfaction', sa.Integer(), nullable=True),
    sa.Column('total_rate', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('email')
    )
    op.create_table('lists',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.username'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    op.create_table('ratings',
    sa.Column('rating_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('course_id', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('difficulty_level', sa.Float(), nullable=False),
    sa.Column('content_density', sa.Integer(), nullable=False),
    sa.Column('content_update', sa.Integer(), nullable=False),
    sa.Column('satisfaction', sa.Integer(), nullable=False),
    sa.Column('total_rate', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.username'], ),
    sa.PrimaryKeyConstraint('rating_id')
    )
    op.create_table('dislikes',
    sa.Column('raitng_id', sa.Integer(), nullable=False),
    sa.Column('liked_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['liked_by'], ['users.username'], ),
    sa.ForeignKeyConstraint(['raitng_id'], ['ratings.rating_id'], ),
    sa.PrimaryKeyConstraint('raitng_id', 'liked_by')
    )
    op.create_table('likes',
    sa.Column('raitng_id', sa.Integer(), nullable=False),
    sa.Column('liked_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['liked_by'], ['users.username'], ),
    sa.ForeignKeyConstraint(['raitng_id'], ['ratings.rating_id'], ),
    sa.PrimaryKeyConstraint('raitng_id', 'liked_by')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    op.drop_table('dislikes')
    op.drop_table('ratings')
    op.drop_table('lists')
    op.drop_table('users')
    op.drop_table('courses')
    # ### end Alembic commands ###
