"""empty message

Revision ID: e6ff4ce94db4
Revises: 0c9f26092c02
Create Date: 2020-10-02 16:21:04.904501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6ff4ce94db4'
down_revision = '0c9f26092c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'content_density',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('courses', 'content_update',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('courses', 'difficulty_level',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('courses', 'satisfaction',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('courses', 'total_rate',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'total_rate',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('courses', 'satisfaction',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('courses', 'difficulty_level',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('courses', 'content_update',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('courses', 'content_density',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
