"""empty message

Revision ID: eef424b2c060
Revises: e6ff4ce94db4
Create Date: 2020-10-21 22:06:22.934597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef424b2c060'
down_revision = 'e6ff4ce94db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('comment', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratings', 'comment')
    # ### end Alembic commands ###
