"""empty message

Revision ID: fb83fc9288bc
Revises: 7c02b6b9f8e2
Create Date: 2020-11-02 10:35:35.382053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb83fc9288bc'
down_revision = '7c02b6b9f8e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dislikes', sa.Column('disliked_by', sa.String(), nullable=False))
    op.drop_constraint('dislikes_liked_by_fkey', 'dislikes', type_='foreignkey')
    op.create_foreign_key(None, 'dislikes', 'users', ['disliked_by'], ['username'])
    op.drop_column('dislikes', 'liked_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dislikes', sa.Column('liked_by', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'dislikes', type_='foreignkey')
    op.create_foreign_key('dislikes_liked_by_fkey', 'dislikes', 'users', ['liked_by'], ['username'])
    op.drop_column('dislikes', 'disliked_by')
    # ### end Alembic commands ###
